id: P143DEE33
initial_creation_type: input
source_metadata:
  title: Rangrik Dorje Series
  language: en
  description: 'Texts by and about the treasure-revealer Rangrik Dorje (rang rig rdo
    rje) alias Kusum Lingpa (sku gsum gling pa, 1847–1903) of Nyarong:'
  volume:
    e8fc7cb3867f490183d137ff052dc227:
      title: An Extremely Concise Barché Lamsel—The Prayer for Clearing Obstacles
        from the Path
      parent: Guru Rinpoche Prayers
    268d92743bc3424fbf245b2ca75717f6:
      title: An Extremely Concise Sampa Lhundrup—Prayer that Spontaneously Fulfils
        All Wishes
      parent: Guru Rinpoche Prayers
    0753716cab4048aba83e9a2703d7374c:
      title: The Seven Lines that Dispel All Obstacles and Enfold All Profundity
      parent: Guru Rinpoche Prayers
    8f391604a5fe4185befa995ec37d0d93:
      title: 'The Spontaneous Fulfilment of All Wishes: Invoking the Great Guru of
        Uḍḍiyāna'
      parent: Guru Rinpoche Prayers
    a7d3c5f2fefa4ae995a3b8f74b5e9a8c:
      title: 'The Wish-Fulfilling Tree: A Prayer to the All-Embodying Lama Tsokye
        Dorje'
      parent: Guru Rinpoche Prayers
    df171950245143f4b2e2fdbadba01cd2:
      title: 'Victory Over All Adversity: A Prayer to Invoke Guru Rinpoche’s Wisdom
        for the Swift Fulfilment of Wishes'
      parent: Guru Rinpoche Prayers
created_at: '2022-03-01T01:19:09.768119'
last_modified_at: '2022-03-01T01:19:09.768125'
